from building import *

cwd = GetCurrentDir() + "/include"
src = Glob('src/*.c')
inc = [cwd]

group = DefineGroup('hwsecurec', src, depend = ['PKG_LITEOS_SDK_USING_HWSECUREC'], CPPPATH = inc)

Return('group')
