from building import *
import os

cwd = GetCurrentDir()
src = Glob('src/*.c')
inc = [cwd + "/include"]

group = DefineGroup('hwsecurec', src, depend = ['PKG_LITEOS_SDK_USING_HWSECUREC'], CPPPATH = inc)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
