from building import *

cwd = GetCurrentDir()
src = []
inc = [cwd]

if GetDepend(['PKG_LITEOS_SDK_USING_DEMO_MEMCPY_S']):
    src += ['memcpy_s_demo.c']

if GetDepend(['PKG_LITEOS_SDK_USING_DEMO_MEMSET_S']):
    src += ['memset_s_demo.c']

group = DefineGroup('hwsecurec-demo', src, depend = ['PKG_LITEOS_SDK_USING_DEMO'], CPPPATH = inc)

Return('group')
